# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### index info
GET http://localhost:8080/shop

### create index
POST http://localhost:8080/shoptest

### fail mapping
GET http://localhost:8080/fail

### shop get
GET http://localhost:8080/shop/12345

### test
GET http://localhost:8080/test

### create index
POST http://localhost:8080/new_shop

### delta index
POST http://localhost:8080/new_shop/delta
Content-Type: application/json

{
    "id" : "99998"
}


### full index
POST http://localhost:8080/new_shop/full
Content-Type: application/json

{
    "startId" : "1",
    "endId" : "10"
}

### search
POST http://localhost:8080/new_shop/search
Content-Type: application/json

{
    "regionCode" : "11680640",
    "categoryCode" : "1",
    "page" : {
        "offset" : 0,
        "size" : 100
    }
}

###